# Generated by Django 5.0.6 on 2025-07-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de entrega'), ('ENTREGADO', 'Entregado'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=30),
        ),
    ]
