# Generated by Django 5.0.6 on 2025-07-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
