# Generated by Django 5.0.6 on 2025-07-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=40, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'default_manager_name': 'objects',
            },
        ),
    ]
